nhmmerpath = "/autorfam/local/hmmer-3.1b2/bin/nhmmer"
eslalistat = "/autorfam/local/hmmer-3.1b2/bin/esl-alistat"
eslref = "/autorfam/local/hmmer-3.1b2/bin/esl-reformat"
rscapepath = "/autorfam/local/rscape_v0.3.3/bin/R-scape"
rnacodepath = "/autorfam/local/RNAcode-0.3/bin/RNAcode"
