nhmmerpath = "/nfs/production/xfam/rfam/rfam_rh7/software/bin/nhmmer"
eslalistat = "/nfs/production/xfam/rfam/rfam_rh7/software/bin/esl-alistat"
eslref = "/nfs/production/xfam/rfam/rfam_rh7/software/bin/esl-reformat"
rscapepath = "/nfs/production/xfam/rfam/rfam_rh7/software/bin/R-scape"
rnacodepath = "/homes/nataquinones/RNAcode-0.3/bin/bin/RNAcode"
